// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDekeaqUaH-F-6H7Kf1grF4ht2qv76n4cY',
    appId: '1:563193643072:web:cff1265725419815241fa5',
    messagingSenderId: '563193643072',
    projectId: 'new-shop-7eca4',
    authDomain: 'new-shop-7eca4.firebaseapp.com',
    storageBucket: 'new-shop-7eca4.firebasestorage.app',
    measurementId: 'G-GHPVZQ4P2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9efufo3bVLCPDqTNjDxQ1ST7EYxXZt6E',
    appId: '1:563193643072:android:fc6199e4c4f43e68241fa5',
    messagingSenderId: '563193643072',
    projectId: 'new-shop-7eca4',
    storageBucket: 'new-shop-7eca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJEfuvWU5AkdOreCpVoBShJbVJV2dxNpM',
    appId: '1:563193643072:ios:a9fafc40365e52ef241fa5',
    messagingSenderId: '563193643072',
    projectId: 'new-shop-7eca4',
    storageBucket: 'new-shop-7eca4.firebasestorage.app',
    iosBundleId: 'com.example.newShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJEfuvWU5AkdOreCpVoBShJbVJV2dxNpM',
    appId: '1:563193643072:ios:a9fafc40365e52ef241fa5',
    messagingSenderId: '563193643072',
    projectId: 'new-shop-7eca4',
    storageBucket: 'new-shop-7eca4.firebasestorage.app',
    iosBundleId: 'com.example.newShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDekeaqUaH-F-6H7Kf1grF4ht2qv76n4cY',
    appId: '1:563193643072:web:6049756821f9c55a241fa5',
    messagingSenderId: '563193643072',
    projectId: 'new-shop-7eca4',
    authDomain: 'new-shop-7eca4.firebaseapp.com',
    storageBucket: 'new-shop-7eca4.firebasestorage.app',
    measurementId: 'G-48VXQCWBLX',
  );
}
